name: tour-project

services:
  tour-client:
    build: .
    image: tour-client:latest
    ports:
      - "8002:8002"
    env_file:
      - .env

networks:
  default:
    name: tour_network
    external: true
